"""add is_locked and allow multiple students per user

Revision ID: 2ba162095400
Revises: 47ea22805848
Create Date: 2026-02-20 16:53:06.886036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba162095400'
down_revision = '47ea22805848'
branch_labels = None
depends_on = None


def upgrade():
    # student table changes
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('ix_student_user_id')
        batch_op.create_index(batch_op.f('ix_student_user_id'), ['user_id'], unique=False)

    # submission table changes
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false'))
        )
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_user_id'))
        batch_op.create_index('ix_student_user_id', ['user_id'], unique=True)

    # ### end Alembic commands ###
